openapi: 3.0.0
info:
  title: Transactions
  version: '1.0'
servers:
  - url: 'http://172.17.0.1'
    description: Docker
paths:
  /v1/transactions/withdraw:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: Saque realizado com sucesso
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      value:
                        type: number
                      banknotes:
                        type: array
                        items:
                          required: []
                          properties: {}
                    required:
                      - value
                      - banknotes
                  success:
                    type: boolean
                required:
                  - data
                  - success
              examples: {}
      operationId: withdraw
      description: Permite o usuário realizar saques de conta corrente ou poupança
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: Request para realização do saque
  /v1/user:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-v1-user
      description: Lista de usuários
    post:
      summary: ''
      operationId: post-v1-user
      responses:
        '201':
          description: OK | Usuário criado com sucesso
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        minLength: 1
                      birthday:
                        type: string
                        minLength: 1
                      document:
                        type: string
                        minLength: 1
                      updated_at:
                        type: string
                        minLength: 1
                      created_at:
                        type: string
                        minLength: 1
                      id:
                        type: number
                    required:
                      - name
                      - birthday
                      - document
                      - updated_at
                      - created_at
                      - id
                  success:
                    type: boolean
                required:
                  - data
                  - success
      description: Criação de um novo usuário
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Nome completo
                document:
                  type: string
                  minLength: 1
                  description: 'Inserir no padrão: 111.222.333-44'
                birthday:
                  type: string
                  minLength: 1
                  description: 'Inserir no padrão: dd/mm/YYYY'
              required:
                - name
                - document
                - birthday
            examples: {}
        description: ''
components:
  schemas: {}
